-- Portable PostgreSQL schema for the self-hosted MST Checker deployment.
--
-- The Supabase migrations remain the historical source of truth for the
-- hosted deployment. This file intentionally contains only PostgreSQL
-- objects used by the self-hosted application; Supabase Auth, RLS, Storage,
-- pg_cron, pg_net and Vault are not required on the Oracle VM.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key,
  email text,
  display_name text,
  role text not null default 'user' check (role in ('admin', 'user')),
  approval_status text not null default 'pending' check (approval_status in ('pending', 'approved', 'blocked')),
  approved_at timestamptz,
  approved_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.taxpayers (
  tax_code text primary key,
  name text,
  org_type text,
  address text,
  tax_department text,
  status text,
  status_group text not null default 'unknown' check (status_group in ('active', 'inactive', 'unknown')),
  source_updated_at timestamptz,
  previous_checked_at timestamptz,
  last_checked_at timestamptz,
  status_changed_at timestamptz,
  last_error text,
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  next_check_at timestamptz,
  raw_current_response jsonb,
  needs_manual_review boolean not null default false,
  manual_review_reason text,
  name_source text not null default 'unknown',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.taxpayer_sources (
  id bigint generated by default as identity primary key,
  tax_code text not null references public.taxpayers(tax_code) on delete cascade,
  source_sheet text not null,
  source_year text,
  source_row integer,
  source_unit_key text,
  source_unit_label text,
  source_unit_marker text,
  source_unit_order integer,
  source_vendor_name text,
  source_note text,
  source_imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (tax_code, source_sheet, source_row)
);

create table if not exists public.taxpayer_source_units (
  source_year text not null check (source_year ~ '^\d{4}$'),
  source_unit_key text not null check (source_unit_key ~ '^([a-z0-9]+-)*[a-z0-9]+$'),
  source_unit_label text not null,
  source_unit_marker text not null,
  source_unit_order integer not null check (source_unit_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (source_year, source_unit_key, source_unit_marker)
);

create table if not exists public.taxpayer_status_history (
  id bigint generated by default as identity primary key,
  tax_code text not null references public.taxpayers(tax_code) on delete cascade,
  old_status text,
  new_status text,
  old_status_group text,
  new_status_group text,
  detected_at timestamptz not null default now(),
  source_updated_at timestamptz,
  note text
);

create table if not exists public.refresh_queue (
  tax_code text primary key references public.taxpayers(tax_code) on delete cascade,
  priority smallint not null default 0,
  state text not null default 'queued' check (state in ('queued', 'running', 'success', 'retry', 'dead_letter', 'cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  run_after timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lookup_audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid,
  tax_code text not null,
  result text not null check (result in ('found', 'not_found', 'error')),
  created_at timestamptz not null default now()
);

create table if not exists public.import_issues (
  id bigint generated by default as identity primary key,
  source_sheet text not null,
  source_row integer,
  raw_tax_code text,
  suggested_tax_code text,
  issue_type text not null,
  resolution_status text not null default 'open' check (resolution_status in ('open', 'resolved', 'ignored')),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  setting_key text primary key,
  setting_value text not null,
  description text,
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.taxpayer_activity_logs (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('taxpayer_added', 'taxpayer_deleted', 'excel_imported', 'taxpayer_code_updated')),
  tax_code text,
  taxpayer_name text,
  source_year text,
  actor_username text not null,
  details jsonb not null default '{}'::jsonb,
  import_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.manual_lookup_sessions (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  tax_code text not null references public.taxpayers(tax_code) on delete cascade,
  upstream_cookie text not null,
  expires_at timestamptz not null,
  candidate_records jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null,
  invoice_number_key text not null unique,
  seller_tax_code text,
  seller_name text,
  invoice_template_number text,
  invoice_symbol text,
  invoice_date text,
  tax_amount numeric(24, 2),
  total_amount numeric(24, 2),
  currency text,
  extracted_text text,
  extracted_payload jsonb,
  source_file_name text not null,
  source_file_mime_type text not null,
  source_file_size integer not null check (source_file_size > 0),
  source_file_sha256 text not null,
  extracted_model text not null,
  verification_status text not null default 'unverified' check (verification_status in ('unverified', 'valid', 'invalid', 'error')),
  verification_message text,
  verification_result jsonb,
  verified_at timestamptz,
  imported_by text not null,
  lookup_url text,
  lookup_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_verification_sessions (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  username text not null,
  upstream_cookie text not null,
  form_action text not null,
  hidden_fields jsonb not null default '[]'::jsonb,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.invoice_scan_usage (
  month_start date primary key,
  scan_count integer not null default 0 check (scan_count >= 0),
  monthly_limit integer not null default 200 check (monthly_limit > 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.taxpayer_excel_imports (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  file_name text not null,
  file_size bigint not null check (file_size > 0),
  actor_username text not null,
  status text not null default 'uploading' check (status in ('uploading', 'previewed', 'committing', 'completed', 'failed', 'cancelled')),
  candidates jsonb not null default '[]'::jsonb,
  preview_stats jsonb not null default '{}'::jsonb,
  source_years jsonb not null default '[]'::jsonb,
  source_units jsonb not null default '[]'::jsonb,
  commit_offset integer not null default 0 check (commit_offset >= 0),
  added_tax_codes jsonb not null default '[]'::jsonb,
  added_count integer not null default 0 check (added_count >= 0),
  updated_count integer not null default 0 check (updated_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  review_count integer not null default 0 check (review_count >= 0),
  error text,
  file_deleted_at timestamptz,
  created_at timestamptz not null default now(),
  previewed_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.purchase_invoice_imports (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  file_name text not null,
  file_size bigint not null check (file_size > 0),
  actor_username text not null,
  status text not null default 'uploading' check (status in ('uploading', 'previewed', 'committing', 'completed', 'failed', 'cancelled')),
  candidates jsonb not null default '[]'::jsonb,
  preview_stats jsonb not null default '{}'::jsonb,
  commit_offset integer not null default 0 check (commit_offset >= 0),
  added_count integer not null default 0 check (added_count >= 0),
  skipped_count integer not null default 0 check (skipped_count >= 0),
  invalid_count integer not null default 0 check (invalid_count >= 0),
  error text,
  file_deleted_at timestamptz,
  created_at timestamptz not null default now(),
  previewed_at timestamptz,
  completed_at timestamptz
);

create table if not exists public.purchase_invoices (
  id uuid primary key default gen_random_uuid(),
  row_fingerprint text not null unique check (char_length(row_fingerprint) between 32 and 255),
  invoice_identity_key text,
  invoice_number text,
  invoice_issue_date date,
  seller_name text,
  seller_tax_code text,
  invoice_symbol text,
  invoice_template_number text,
  goods_services text,
  net_amount numeric(24, 2),
  deductible_vat_amount numeric(24, 2),
  accounting_voucher text,
  accounting_date date,
  tax_rate text,
  description text,
  department_code text,
  source_sheet text not null,
  source_row integer not null check (source_row > 0),
  source_stt integer,
  raw_payload jsonb not null default '{}'::jsonb,
  import_id uuid references public.purchase_invoice_imports(id) on delete set null,
  imported_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.taxpayer_evidence (
  tax_code text primary key references public.taxpayers(tax_code) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  content_type text not null,
  file_size bigint not null check (file_size > 0 and file_size <= 4194304),
  uploaded_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists taxpayer_sources_tax_year_null_row_idx
  on public.taxpayer_sources (tax_code, source_year, coalesce(source_row, -1));
create index if not exists taxpayers_status_group_idx on public.taxpayers(status_group);
create index if not exists taxpayers_next_check_idx on public.taxpayers(next_check_at);
create index if not exists taxpayers_manual_review_idx on public.taxpayers(needs_manual_review, updated_at desc);
create index if not exists refresh_queue_schedule_idx on public.refresh_queue(state, run_after, priority desc);
create index if not exists lookup_audit_logs_user_created_idx on public.lookup_audit_logs(user_id, created_at desc);
create index if not exists lookup_audit_logs_tax_code_idx on public.lookup_audit_logs(tax_code, created_at desc);
create index if not exists taxpayer_sources_year_idx on public.taxpayer_sources(source_year);
create index if not exists taxpayer_sources_year_unit_idx on public.taxpayer_sources(source_year, source_unit_order, source_unit_key);
create index if not exists taxpayer_sources_latest_name_idx on public.taxpayer_sources(tax_code, source_imported_at desc, id desc);
create index if not exists taxpayer_source_units_year_order_idx on public.taxpayer_source_units(source_year, source_unit_order, source_unit_marker, source_unit_key);
create index if not exists taxpayer_activity_logs_created_at_idx on public.taxpayer_activity_logs(created_at desc);
create index if not exists taxpayer_activity_logs_tax_code_idx on public.taxpayer_activity_logs(tax_code, created_at desc);
create unique index if not exists taxpayer_activity_logs_import_id_idx on public.taxpayer_activity_logs(import_id) where action = 'excel_imported' and import_id is not null;
create index if not exists manual_lookup_sessions_expiry_idx on public.manual_lookup_sessions(expires_at);
create index if not exists invoices_created_at_idx on public.invoices(created_at desc);
create index if not exists invoices_status_idx on public.invoices(verification_status, created_at desc);
create index if not exists invoices_seller_tax_code_idx on public.invoices(seller_tax_code);
create index if not exists invoice_verification_sessions_expiry_idx on public.invoice_verification_sessions(expires_at);
create index if not exists invoice_verification_sessions_user_idx on public.invoice_verification_sessions(username, created_at desc);
create index if not exists taxpayer_excel_imports_actor_created_idx on public.taxpayer_excel_imports(actor_username, created_at desc);
create index if not exists taxpayer_excel_imports_status_created_idx on public.taxpayer_excel_imports(status, created_at desc);
create index if not exists purchase_invoice_imports_actor_created_idx on public.purchase_invoice_imports(actor_username, created_at desc);
create index if not exists purchase_invoice_imports_status_created_idx on public.purchase_invoice_imports(status, created_at desc);
create index if not exists purchase_invoices_issue_date_idx on public.purchase_invoices(invoice_issue_date desc nulls last, created_at desc);
create index if not exists purchase_invoices_seller_tax_code_idx on public.purchase_invoices(seller_tax_code);
create index if not exists purchase_invoices_invoice_number_idx on public.purchase_invoices(invoice_number);
create index if not exists purchase_invoices_identity_key_idx on public.purchase_invoices(invoice_identity_key) where invoice_identity_key is not null;
create index if not exists purchase_invoices_import_id_idx on public.purchase_invoices(import_id, created_at desc);
create index if not exists taxpayer_evidence_updated_at_idx on public.taxpayer_evidence(updated_at desc);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists taxpayers_set_updated_at on public.taxpayers;
create trigger taxpayers_set_updated_at before update on public.taxpayers for each row execute function public.set_updated_at();
drop trigger if exists refresh_queue_set_updated_at on public.refresh_queue;
create trigger refresh_queue_set_updated_at before update on public.refresh_queue for each row execute function public.set_updated_at();
drop trigger if exists app_settings_set_updated_at on public.app_settings;
create trigger app_settings_set_updated_at before update on public.app_settings for each row execute function public.set_updated_at();
drop trigger if exists taxpayer_source_units_set_updated_at on public.taxpayer_source_units;
create trigger taxpayer_source_units_set_updated_at before update on public.taxpayer_source_units for each row execute function public.set_updated_at();
drop trigger if exists invoices_set_updated_at on public.invoices;
create trigger invoices_set_updated_at before update on public.invoices for each row execute function public.set_updated_at();
drop trigger if exists purchase_invoices_set_updated_at on public.purchase_invoices;
create trigger purchase_invoices_set_updated_at before update on public.purchase_invoices for each row execute function public.set_updated_at();
drop trigger if exists taxpayer_evidence_set_updated_at on public.taxpayer_evidence;
create trigger taxpayer_evidence_set_updated_at before update on public.taxpayer_evidence for each row execute function public.set_updated_at();

insert into public.app_settings (setting_key, setting_value, description)
values
  ('primary_tax_lookup_endpoint', 'https://api.xinvoice.vn/gdt-api/tax-payer/{taxCode}', 'Endpoint tra cứu MST chính'),
  ('fallback_tax_lookup_endpoint', 'https://api.vietqr.io/v2/business/{taxCode}', 'Endpoint tra cứu MST dự phòng'),
  ('refresh_worker_paused', 'true', 'Tạm dừng hàng đợi cập nhật MST')
on conflict (setting_key) do nothing;

commit;
