-- Persistent audit trail for manual taxpayer catalogue changes.
-- This table deliberately has no foreign key to taxpayers so deletion events
-- remain visible after the related MST and its source rows are removed.

create table if not exists public.taxpayer_activity_logs (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('taxpayer_added', 'taxpayer_deleted')),
  tax_code text not null,
  taxpayer_name text,
  source_year text,
  actor_username text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists taxpayer_activity_logs_created_at_idx
  on public.taxpayer_activity_logs(created_at desc);

create index if not exists taxpayer_activity_logs_tax_code_idx
  on public.taxpayer_activity_logs(tax_code, created_at desc);

alter table public.taxpayer_activity_logs enable row level security;

comment on table public.taxpayer_activity_logs is
  'Audit log for successful manual additions and deletions of taxpayer records.';
