-- MST Checker initial schema.
-- Run this migration before running the local seed generated by scripts/generate-seed.mjs.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'user' check (role in ('admin', 'user')),
  approval_status text not null default 'pending' check (approval_status in ('pending', 'approved', 'blocked')),
  approved_at timestamptz,
  approved_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.taxpayers (
  tax_code text primary key,
  name text,
  org_type text,
  address text,
  tax_department text,
  status text,
  status_group text not null default 'unknown' check (status_group in ('active', 'inactive', 'unknown')),
  source_updated_at timestamptz,
  last_checked_at timestamptz,
  status_changed_at timestamptz,
  last_error text,
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  next_check_at timestamptz,
  raw_current_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.taxpayer_sources (
  id bigint generated by default as identity primary key,
  tax_code text not null references public.taxpayers(tax_code) on delete cascade,
  source_sheet text not null,
  source_year text,
  source_row integer,
  source_vendor_name text,
  source_note text,
  created_at timestamptz not null default now(),
  unique (tax_code, source_sheet, source_row)
);

create table if not exists public.taxpayer_status_history (
  id bigint generated by default as identity primary key,
  tax_code text not null references public.taxpayers(tax_code) on delete cascade,
  old_status text,
  new_status text,
  old_status_group text,
  new_status_group text,
  detected_at timestamptz not null default now(),
  source_updated_at timestamptz,
  note text
);

create table if not exists public.refresh_queue (
  tax_code text primary key references public.taxpayers(tax_code) on delete cascade,
  priority smallint not null default 0,
  state text not null default 'queued' check (state in ('queued', 'running', 'success', 'retry', 'dead_letter')),
  attempts integer not null default 0 check (attempts >= 0),
  run_after timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lookup_audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tax_code text not null,
  result text not null check (result in ('found', 'not_found', 'error')),
  created_at timestamptz not null default now()
);

create table if not exists public.import_issues (
  id bigint generated by default as identity primary key,
  source_sheet text not null,
  source_row integer,
  raw_tax_code text,
  suggested_tax_code text,
  issue_type text not null,
  resolution_status text not null default 'open' check (resolution_status in ('open', 'resolved', 'ignored')),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists taxpayers_status_group_idx on public.taxpayers(status_group);
create index if not exists taxpayers_next_check_idx on public.taxpayers(next_check_at);
create index if not exists refresh_queue_schedule_idx on public.refresh_queue(state, run_after, priority desc);
create index if not exists lookup_audit_logs_user_created_idx on public.lookup_audit_logs(user_id, created_at desc);
create index if not exists lookup_audit_logs_tax_code_idx on public.lookup_audit_logs(tax_code, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists taxpayers_set_updated_at on public.taxpayers;
create trigger taxpayers_set_updated_at
before update on public.taxpayers
for each row execute function public.set_updated_at();

drop trigger if exists refresh_queue_set_updated_at on public.refresh_queue;
create trigger refresh_queue_set_updated_at
before update on public.refresh_queue
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = coalesce(public.profiles.display_name, excluded.display_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_approved_user()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and approval_status = 'approved'
  );
$$;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and approval_status = 'approved'
  );
$$;

create or replace function public.request_taxpayer_refresh(p_tax_code text)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  normalized_code text := regexp_replace(trim(p_tax_code), '\s+', '', 'g');
begin
  if not public.is_approved_user() then
    raise exception 'approved account required' using errcode = '42501';
  end if;

  if not exists (select 1 from public.taxpayers where tax_code = normalized_code) then
    return;
  end if;

  insert into public.refresh_queue (tax_code, priority, state, run_after)
  values (normalized_code, 10, 'queued', now())
  on conflict (tax_code) do update
  set priority = greatest(public.refresh_queue.priority, excluded.priority),
      state = case
        when public.refresh_queue.state in ('success', 'dead_letter') then 'queued'
        else public.refresh_queue.state
      end,
      run_after = least(public.refresh_queue.run_after, excluded.run_after),
      last_error = null,
      updated_at = now();
end;
$$;

create or replace function public.claim_refresh_batch(p_limit integer default 10)
returns setof public.refresh_queue
language plpgsql
security definer set search_path = public
as $$
begin
  return query
  with candidate_rows as (
    select q.tax_code
    from public.refresh_queue q
    where q.state in ('queued', 'retry')
      and q.run_after <= now()
    order by q.priority desc, q.run_after asc
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 10), 100))
  )
  update public.refresh_queue q
  set state = 'running',
      locked_at = now(),
      updated_at = now()
  from candidate_rows c
  where q.tax_code = c.tax_code
  returning q.*;
end;
$$;

alter table public.profiles enable row level security;
alter table public.taxpayers enable row level security;
alter table public.taxpayer_sources enable row level security;
alter table public.taxpayer_status_history enable row level security;
alter table public.refresh_queue enable row level security;
alter table public.lookup_audit_logs enable row level security;
alter table public.import_issues enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin_user());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists taxpayers_select_approved on public.taxpayers;
create policy taxpayers_select_approved on public.taxpayers
for select to authenticated
using (public.is_approved_user());

drop policy if exists taxpayer_sources_select_approved on public.taxpayer_sources;
create policy taxpayer_sources_select_approved on public.taxpayer_sources
for select to authenticated
using (public.is_approved_user());

drop policy if exists taxpayer_history_select_approved on public.taxpayer_status_history;
create policy taxpayer_history_select_approved on public.taxpayer_status_history
for select to authenticated
using (public.is_approved_user());

drop policy if exists audit_insert_approved on public.lookup_audit_logs;
create policy audit_insert_approved on public.lookup_audit_logs
for insert to authenticated
with check (user_id = auth.uid() and public.is_approved_user());

drop policy if exists audit_select_own on public.lookup_audit_logs;
create policy audit_select_own on public.lookup_audit_logs
for select to authenticated
using (user_id = auth.uid() or public.is_admin_user());

drop policy if exists import_issues_admin_select on public.import_issues;
create policy import_issues_admin_select on public.import_issues
for select to authenticated
using (public.is_admin_user());

grant usage on schema public to authenticated;
grant select on public.profiles, public.taxpayers, public.taxpayer_sources, public.taxpayer_status_history to authenticated;
grant insert, select on public.lookup_audit_logs to authenticated;
grant execute on function public.request_taxpayer_refresh(text) to authenticated;

revoke all on function public.claim_refresh_batch(integer) from public, anon, authenticated;
grant execute on function public.claim_refresh_batch(integer) to service_role;

comment on table public.taxpayers is 'Current normalized status for one row per tax code.';
comment on table public.taxpayer_sources is 'Source workbook occurrences, including duplicate rows across years/sheets.';
comment on table public.taxpayer_status_history is 'Only material status changes, not every successful refresh.';
comment on table public.refresh_queue is 'Rate-limited background refresh queue for the XInvoice worker.';
